apply plugin: 'com.android.library'

group = 'expo.modules.videoencoder'
version = '1.0.23'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "expo.modules.videoencoder"
  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
    compileSdkVersion safeExtGet("compileSdkVersion", 34)
    targetSdkVersion safeExtGet("targetSdkVersion", 34)
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
  kotlinOptions {
    jvmTarget = JavaVersion.VERSION_17.majorVersion
  }
}
